import {test} from 'node:test';
import assert from 'node:assert/strict';
import {rankedMeetingWindows} from './availability-matching.ts';
const members=['a','b','c'].map(id=>({id,name:id,email:id,role:'member'}));
const r=(startHour,endHour)=>[{startHour,endHour}];
const data={a:{Mon:r(9,10),Tue:r(9,12)},b:{Mon:r(9,10),Tue:r(9,11)},c:{Mon:r(9,10),Tue:r(9,10)}};
test('weekday filter excludes higher-ranked days outside selection',()=>{const result=rankedMeetingWindows(members,data,60,['Tue']);assert.ok(result.windows.every(w=>w.day==='Tue'));assert.equal(result.windows[0].dayIndex,1);});
test('no duration returns three attendance levels, not only tied maximum',()=>{const result=rankedMeetingWindows(members,data,0,['Tue']);assert.deepEqual(result.windows.map(w=>w.count),[3,2,1]);assert.deepEqual(result.windows.map(w=>[w.start,w.end]),[[9,10],[10,11],[11,12]]);assert.deepEqual(result.windows[1].attendees.map(m=>m.id),['a','b']);});
test('fixed duration includes lower attendance alternatives',()=>{const result=rankedMeetingWindows(members,data,60,['Tue']);assert.equal(result.windows[0].count,3);assert.ok(result.windows.some(w=>w.count===2));assert.ok(result.windows.some(w=>w.count===1));});
test('no weekdays returns an empty result',()=>assert.deepEqual(rankedMeetingWindows(members,data,0,[]),{maximum:0,windows:[]}));
