"use client";
import {useState} from 'react';
import type {Workspace} from '../lib/workspace';
import {dateKey} from './EventComposer';
import s from './OrgCalendar.module.css';
export default function OrgCalendar({data,email,shared=false,personal=false}:{data:Workspace;email:string;shared?:boolean;personal?:boolean}){
 const [month,setMonth]=useState(()=>new Date(new Date().getFullYear(),new Date().getMonth(),1));const [day,setDay]=useState('');const [mine,setMine]=useState(personal);
 const events=(data.events||[]).filter(e=>!mine||e.participantEmails.includes(email)).sort((a,b)=>a.start.localeCompare(b.start));
 const monthEvents=events.filter(e=>{const d=new Date(e.start);return d.getFullYear()===month.getFullYear()&&d.getMonth()===month.getMonth();});
 const shown=monthEvents.filter(e=>!day||dateKey(new Date(e.start))===day);
 const offset=(month.getDay()+6)%7;const count=new Date(month.getFullYear(),month.getMonth()+1,0).getDate();
 const embedUrl=`https://calendar.google.com/calendar/embed?${new URLSearchParams({src:data.calendarId,ctz:Intl.DateTimeFormat().resolvedOptions().timeZone,mode:'WEEK',showTitle:'0',showPrint:'0',wkst:'2'})}`;

 return <section className={s.panel}>{data.calendarId&&!personal&&<details><summary>Connected Google Calendar</summary><iframe className={s.googleEmbed} src={embedUrl} title="Organization Google Calendar"/><a href={embedUrl} target="_blank" rel="noreferrer">Open Google Calendar ↗</a></details>}<header><div><h2>{personal?"My Calendar":"Organization calendar"}</h2><p>Scheduled meetings, all in one place.</p></div>{!personal&&<label><input type="checkbox" checked={mine} onChange={e=>setMine(e.target.checked)}/> My events only</label>}</header><header><div className={s.toolbar}><button aria-label="Previous month" onClick={()=>{setMonth(new Date(month.getFullYear(),month.getMonth()-1,1));setDay('');}}>←</button><strong>{month.toLocaleDateString('en-US',{month:'long',year:'numeric'})}</strong><button aria-label="Next month" onClick={()=>{setMonth(new Date(month.getFullYear(),month.getMonth()+1,1));setDay('');}}>→</button></div><button onClick={()=>setDay('')}>All events this month</button></header><div className={s.month}>{['Mon','Tue','Wed','Thu','Fri','Sat','Sun'].map(d=><span key={d}>{d}</span>)}{Array.from({length:offset},(_,i)=><div key={`blank-${i}`}/>)}{Array.from({length:count},(_,i)=>{const key=dateKey(new Date(month.getFullYear(),month.getMonth(),i+1));const n=monthEvents.filter(e=>dateKey(new Date(e.start))===key).length;return <button key={key} aria-label={`${key}, ${n} events`} aria-pressed={day===key} onClick={()=>setDay(key)}>{i+1}{n>0&&<small>{n} event{n===1?'':'s'}</small>}</button>;})}</div><div className={s.agenda}>{!shown.length&&<p>No events {day?'on this date':'this month'}. Select a time in Team Availability to schedule one.</p>}{shown.map(event=><article className={s.event} key={event.id}><h3>{event.title}</h3><p>{new Date(event.start).toLocaleString()} – {new Date(event.end).toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'})} · {event.timeZone}</p><p>{(event.participantNames||event.participantIds.map(id=>data.members.find(m=>m.id===id)?.name||'Former member')).join(', ')}</p>{event.description&&<p style={{whiteSpace:'pre-wrap'}}>{event.description}</p>}<p>{event.googleStatus==='synced'?'Saved to Google Calendar':event.googleStatus==='local'?'Site calendar':event.googleStatus==='pending'?'Google sync pending':'Site calendar · Google sync failed'}</p>{event.googleLink&&<a href={event.googleLink} target="_blank" rel="noreferrer">Open in Google Calendar ↗</a>}{event.syncError&&<p role="alert">{event.syncError}</p>}</article>)}</div><p>{shared?"Site events are shared on this server.":"Site events currently stay in this browser."} Connected Google events are shared through Google Calendar permissions. Times display in {Intl.DateTimeFormat().resolvedOptions().timeZone}.</p></section>;
}
