"use client";
import {useRef,useState,type ReactNode,type FormEvent} from 'react';
import {readOrganizations,saveOrganizations} from '../lib/organizations';
import {dateKey} from './EventComposer';
import {persistWorkspace} from '../lib/workspace';
import s from './OrgCalendar.module.css';
export default function QuickCreate({buttonClassName,hideCaption=false,children}:{buttonClassName?:string;hideCaption?:boolean;children?:ReactNode}){
 const localZone=Intl.DateTimeFormat().resolvedOptions().timeZone;const zones=[...new Set([localZone,'UTC',...Intl.supportedValuesOf('timeZone')])];
 const dialog=useRef<HTMLDialogElement>(null);const [busy,setBusy]=useState(false);const [error,setError]=useState('');
 async function create(e:FormEvent<HTMLFormElement>){e.preventDefault();if(busy)return;setBusy(true);setError('');try{const form=new FormData(e.currentTarget),name=String(form.get('name')).trim();const from=new Date(`${form.get('from')}T12:00`),to=new Date(`${form.get('to')}T12:00`);if(!Number.isFinite(from.getTime())||!Number.isFinite(to.getTime())||to<from)throw new Error('Choose an end date on or after the start date.');const dates:string[]=[];for(const d=new Date(from);d<=to;d.setDate(d.getDate()+1)){dates.push(dateKey(d));if(dates.length>14)throw new Error('Choose up to 14 candidate dates.');}const r=await fetch('/api/organization-access',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'quick-create',name,dates,timeZone:form.get('timeZone'),startHour:Number(form.get('startHour')),endHour:Number(form.get('endHour'))})});const result=await r.json();if(!r.ok)throw new Error(result.error);const org={...result.org,inviteToken:result.token,visited:Date.now()};saveOrganizations([...readOrganizations(),org]);persistWorkspace(org.id,result.workspace);let note='Your quick meet is ready. Use Copy link to invite people.';try{await navigator.clipboard.writeText(`${location.origin}/join#token=${encodeURIComponent(result.token)}`);note='Meeting created · Invite link copied! Share it with your group.';}catch{}location.assign(`/organizations/${org.id}?created=${encodeURIComponent(note)}`);}catch(e){setError(e instanceof Error?e.message:'Could not create organization.');setBusy(false);}}
 return <><button type="button" className={buttonClassName||s.quickButton} onClick={()=>dialog.current?.showModal()}>{children || <>Quick meet <span aria-hidden="true">→</span></>}</button>{!hideCaption&&<p className={s.quickCaption}>No account needed · Just share a link</p>}<dialog ref={dialog} className={s.composer} onCancel={e=>{if(busy)e.preventDefault();}}><header><h2>Plan a quick meet</h2><button disabled={busy} onClick={()=>dialog.current?.close()} aria-label="Close quick create">×</button></header><form onSubmit={create}><p>Name your meeting and choose the dates that could work.</p><label>Meeting name<input autoFocus name="name" required maxLength={80} placeholder="e.g. Weekend study group"/></label><div className={s.fields}><label>From date<input name="from" type="date" required defaultValue={dateKey(new Date())}/></label><label>To date<input name="to" type="date" required defaultValue={dateKey(new Date(Date.now()+2*86400000))}/></label></div><div className={s.quickTimes}><label>From<select name="startHour" defaultValue="9">{Array.from({length:24},(_,h)=><option key={h} value={h}>{String(h).padStart(2,'0')}:00</option>)}</select></label><label>Until<select name="endHour" defaultValue="18">{Array.from({length:24},(_,i)=>i+1).map(h=><option key={h} value={h}>{String(h).padStart(2,'0')}:00</option>)}</select></label><label>Timezone<select name="timeZone" defaultValue={localZone}>{zones.map(zone=><option key={zone}>{zone}</option>)}</select></label></div><small>Everyone sees these times in the selected timezone. Up to 14 candidate dates. Share the link; everyone adds their own times without registering.</small>{error&&<p role="alert">{error}</p>}<button disabled={busy} className={s.primary}>{busy?'Creating…':'Create & copy invite link'}</button></form></dialog></>;
}
